## Chicago city Crime prediction part 01

### Creating a sample file and merging social economic indicators


The original file has over 7M lines of data, and around 1 gigabyte of info. Unfortunatly it is not viable to handle so much information.

We added a filter in their website to get crimes between 2014 - 2019 so the file reduced its size to 3M lines of data.

We will create a sample file to describe the values from these years without losing so much information about the population and making easier to explore the data.

### About the Chicago Crime Dataset:


##### Below some of the description of the columns found in the dataset


<strong> ID </strong> - Unique identifier for the record.

 <strong> Case Number </strong>  - The Chicago Police Department RD Number (Records Division Number), which is unique to the incident.

 <strong>  Date </strong> - Date when the incident occurred. this is sometimes a best estimate.

<strong> Block </strong> - The partially redacted address where the incident occurred, placing it on the same block as the actual address.

<strong> IUCR </strong> - The Illinois Unifrom Crime Reporting code. This is directly linked to the Primary Type and Description. See the list of IUCR codes at https://data.cityofchicago.org/d/c7ck-438e.

<strong> Primary Type </strong> - The primary description of the IUCR code.

<strong> Description </strong> - The secondary description of the IUCR code, a subcategory of the primary description.

<strong> Location Description </strong> - Description of the location where the incident occurred.

<strong> Arrest</strong> - Indicates whether an arrest was made.

<strong> Domestic </strong> - Indicates whether the incident was domestic-related as defined by the Illinois Domestic Violence Act.

<strong> Beat </strong> - Indicates the beat where the incident occurred. A beat is the smallest police geographic area â€“ each beat has a dedicated police beat car. Three to five beats make up a police sector, and three sectors make up a police district. The Chicago Police Department has 22 police districts. See the beats at https://data.cityofchicago.org/d/aerh-rz74.

<strong> District </strong> - Indicates the police district where the incident occurred. See the districts at https://data.cityofchicago.org/d/fthy-xz3r.

<strong> Ward </strong> - The ward (City Council district) where the incident occurred. See the wards at https://data.cityofchicago.org/d/sp34-6z76.

<strong> Community Area </strong> - Indicates the community area where the incident occurred. Chicago has 77 community areas. See the community areas at https://data.cityofchicago.org/d/cauq-8yn6.

<strong> FBI Code </strong> - Indicates the crime classification as outlined in the FBI's National Incident-Based Reporting System (NIBRS). See the Chicago Police Department listing of these classifications at http://gis.chicagopolice.org/clearmap_crime_sums/crime_types.html.

<strong> X Coordinate </strong> - The x coordinate of the location where the incident occurred in State Plane Illinois East NAD
1983 projection. This location is shifted from the actual location for partial redaction but falls on the same block.

<strong> Y Coordinate </strong> - The y coordinate of the location where the incident occurred in State Plane Illinois East NAD 1983 projection. This location is shifted from the actual location for partial redaction but falls on the same block.

<strong> Year</strong> - Year the incident occurred.

<strong> Updated On </strong>- Date and time the record was last updated.

<strong> Latitude </strong>- The latitude of the location where the incident occurred. This location is shifted from the actual location for partial redaction but falls on the same block.

<strong> Longitude</strong> - The longitude of the location where the incident occurred. This location is shifted from the actual location for partial redaction but falls on the same block.

<strong> Location</strong> - The location where the incident occurred in a format that allows for creation of maps and other geographic operations on this data portal.

In [1]:
import pandas as pd
import numpy
from random import sample
pd.options.display.max_columns = None

### Appling Pareto's principal.
Instead working with 100% of data, we will try to describe the population using only 20% of the data, let's check if this works.

In [2]:
directory = open('directory.txt', 'r').read() #directory is in another HD

In [3]:
crime_population =  pd.read_csv(directory)

In [4]:
(len(crime_population))*0.2

667121.8

In [5]:
def pd_read():
    filename = directory
    n = sum(1 for line in open(filename)) - 1 #number of records in file (excludes header)
    s = 667122 #desired sample size
    skip = sorted(sample(range(1,n+1),n-s)) #the 0-indexed header will not be included in the skip list
    df = pd.read_csv(filename, skiprows=skip)
    df.to_csv("crime_sample.csv")

In [6]:
pd_read()

In [7]:
# DF IS A SAMPLE OF 20% OF THE DATA OF THE DATASET FROM 2009 TO 2019 FILE SIZE REDUCED AROUND 80%
df = pd.read_csv('./crime_sample.csv')

Testing data loss from the source to the sample, seems quite low

In [8]:
test = crime_population['Primary Type'].value_counts(normalize=True)[:20]

In [9]:
test1 = df['Primary Type'].value_counts(normalize=True)[:20]

In [33]:
pd.DataFrame((test1 - test)*100) # percentage loss by selecting sample size of 20% of the dataframe

                                  Primary Type
THEFT                                -0.043987
BATTERY                              -0.015505
CRIMINAL DAMAGE                      -0.024616
NARCOTICS                             0.022782
ASSAULT                               0.014148
OTHER OFFENSE                        -0.004769
BURGLARY                              0.038492
DECEPTIVE PRACTICE                    0.015468
MOTOR VEHICLE THEFT                   0.009982
ROBBERY                               0.002937
CRIMINAL TRESPASS                     0.002967
WEAPONS VIOLATION                     0.001289
PUBLIC PEACE VIOLATION                0.004647
OFFENSE INVOLVING CHILDREN           -0.019817
PROSTITUTION                          0.007225
CRIM SEXUAL ASSAULT                   0.003807
INTERFERENCE WITH PUBLIC OFFICER     -0.006775
SEX OFFENSE                           0.002368
HOMICIDE                             -0.007855
GAMBLING                              0.003238

In [11]:
df.head(5)

,Unnamed: 0,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,0,10224740,HY411595,09/05/2015 12:45:00 PM,035XX W BARRY AVE,2023,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,1412,14.0,35.0,21.0,18,1152037,1920384,2015,02/10/2018 03:50:01 PM,41.937406,-87.716650,"(41.937405765, -87.716649687)"
1,1,10224749,HY411626,09/05/2015 11:00:00 AM,052XX N MILWAUKEE AVE,0460,BATTERY,SIMPLE,SMALL RETAIL STORE,False,False,1623,16.0,45.0,11.0,08B,1137969,1934340,2015,02/10/2018 03:50:01 PM,41.975968,-87.768014,"(41.975968415, -87.768014257)"
2,2,10224773,HY411685,09/05/2015 07:00:00 AM,029XX W FIFTH AVE,0620,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,1124,11.0,2.0,27.0,05,1156926,1899592,2015,02/10/2018 03:50:01 PM,41.880253,-87.699247,"(41.880252868, -87.69924661)"
3,3,10224778,HY411675,09/05/2015 02:44:00 PM,047XX N KEELER AVE,0560,ASSAULT,SIMPLE,SIDEWALK,True,False,1722,17.0,39.0,14.0,08A,1147525,1931300,2015,02/10/2018 03:50:01 PM,41.967448,-87.732951,"(41.967448012, -87.732951137)"
4,4,10224781,HY411499,09/05/2015 11:20:00 AM,026XX W HOLLYWOOD AVE,0320,ROBBERY,STRONGARM - NO WEAPON,STREET,False,False,2011,20.0,40.0,2.0,03,1157555,1937753,2015,02/10/2018 03:50:01 PM,41.984957,-87.695895,"(41.984956576, -87.69589518)"

In [12]:
crime_population.describe() #ID COLUMNS CAN BE IGNORED

,ID,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude
count,3.335609e+06,3.335609e+06,3.335608e+06,3.335541e+06,3.335032e+06,3.335609e+06,3.335609e+06,3.335609e+06,3.335609e+06,3.335609e+06
mean,9.330108e+06,1.167567e+03,1.128275e+01,2.292897e+01,3.740503e+01,1.164537e+06,1.885678e+06,2.013549e+03,4.184190e+01,-8.767173e+01
std,1.584472e+06,6.988085e+02,6.938718e+00,1.383026e+01,2.150342e+01,1.739854e+04,3.288823e+04,3.197696e+00,9.050732e-02,6.292675e-02
min,4.890000e+03,1.110000e+02,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.009000e+03,3.661945e+01,-9.168657e+01
25%,8.000133e+06,6.140000e+02,6.000000e+00,1.000000e+01,2.300000e+01,1.152813e+06,1.858808e+06,2.011000e+03,4.176800e+01,-8.771429e+01
50%,9.317255e+06,1.031000e+03,1.000000e+01,2.300000e+01,3.200000e+01,1.166132e+06,1.891566e+06,2.013000e+03,4.185827e+01,-8.766583e+01
75%,1.073346e+07,1.723000e+03,1.700000e+01,3.400000e+01,5.600000e+01,1.176365e+06,1.909030e+06,2.016000e+03,4.190621e+01,-8.762807e+01
max,1.253669e+07,2.535000e+03,3.100000e+01,5.000000e+01,7.700000e+01,1.205119e+06,1.951573e+06,2.019000e+03,4.202271e+01,-8.752453e+01

In [13]:
df.describe() # PARETO PRINCIPAL CAN BE USED IN THIS AS MOST NUMERIC VALUES STAYS THE SAME

,Unnamed: 0,ID,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude
count,667122.000000,6.671220e+05,667122.000000,667121.000000,667113.000000,666996.000000,6.671220e+05,6.671220e+05,667122.000000,667122.000000,667122.000000
mean,333560.500000,9.329904e+06,1167.530855,11.284965,22.926979,37.395410,1.164511e+06,1.885673e+06,2013.546095,41.841883,-87.671822
std,192581.677478,1.581095e+06,698.518360,6.935720,13.831108,21.497611,1.769902e+04,3.328809e+04,3.193881,0.091621,0.063924
min,0.000000,4.895000e+03,111.000000,1.000000,1.000000,0.000000,0.000000e+00,0.000000e+00,2009.000000,36.619446,-91.686566
25%,166780.250000,8.001196e+06,614.000000,6.000000,10.000000,23.000000,1.152801e+06,1.858798e+06,2011.000000,41.767957,-87.714349
50%,333560.500000,9.316168e+06,1031.000000,10.000000,23.000000,32.000000,1.166098e+06,1.891577e+06,2013.000000,41.858301,-87.665878
75%,500340.750000,1.073036e+07,1722.000000,17.000000,34.000000,56.000000,1.176365e+06,1.909062e+06,2016.000000,41.906308,-87.628074
max,667121.000000,1.253669e+07,2535.000000,31.000000,50.000000,77.000000,1.205119e+06,1.951517e+06,2019.000000,42.022559,-87.524529

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667122 entries, 0 to 667121
Data columns (total 23 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Unnamed: 0            667122 non-null  int64
 1   ID                    667122 non-null  int64
 2   Case Number           667122 non-null  object
 3   Date                  667122 non-null  object
 4   Block                 667122 non-null  object
 5   IUCR                  667122 non-null  object
 6   Primary Type          667122 non-null  object
 7   Description           667122 non-null  object
 8   Location Description  666314 non-null  object
 9   Arrest                667122 non-null  bool
 10  Domestic              667122 non-null  bool
 11  Beat                  667122 non-null  int64
 12  District              667121 non-null  float64
 13  Ward                  667113 non-null  float64
 14  Community Area        666996 non-null  float64
 15  FBI Code              667122 non-null  object
 16  X Coordinate          667122 non-null  int64
 17  Y Coordinate          667122 non-null  int64
 18  Year                  667122 non-null  int64
 19  Updated On            667122 non-null  object
 20  Latitude              667122 non-null  float64
 21  Longitude             667122 non-null  float64
 22  Location              667122 non-null  object
dtypes: bool(2), float64(5), int64(6), object(10)
memory usage: 108.2+ MB

# Data cleaning


### Droping columns that will no be used during the analysis

In [15]:
## Description of the crimes, giving further information about the cases.
df['Description'].unique()

array(['POSS: HEROIN(BRN/TAN)', 'SIMPLE', 'UNLAWFUL ENTRY',
       'STRONGARM - NO WEAPON', 'OVER $500', 'COUNTERFEIT CHECK',
       'DOMESTIC BATTERY SIMPLE', 'MANU/DELIVER: HEROIN (WHITE)',
       'POSS: CRACK', 'FORCIBLE ENTRY', 'POSS: CANNABIS 30GMS OR LESS',
       '$500 AND UNDER', 'RETAIL THEFT', 'HARASSMENT BY TELEPHONE',
       'PUBLIC INDECENCY', 'TO VEHICLE', 'AUTOMOBILE',
       'FINANCIAL IDENTITY THEFT OVER $ 300', 'FRAUD OR CONFIDENCE GAME',
       'PURSE-SNATCHING', 'TELEPHONE THREAT', 'TO LAND',
       'SEX ASSLT OF CHILD BY FAM MBR', 'MANU/DEL:CANNABIS OVER 10 GMS',
       'TO PROPERTY', 'AGGRAVATED:KNIFE/CUTTING INSTR',
       'CRIMINAL DEFACEMENT', 'FROM BUILDING', 'POSS: SYNTHETIC DRUGS',
       'POSS: HEROIN(WHITE)', 'RECKLESS CONDUCT', 'AGGRAVATED: HANDGUN',
       'PAROLE VIOLATION', 'LICENSE VIOLATION', 'ARMED: HANDGUN',
       'GAME/DICE', 'ENDANGERING LIFE/HEALTH CHILD',
       'FOUND SUSPECT NARCOTICS', 'AGG PO HANDS ETC SERIOUS INJ',
       'VIOLATE ORDER OF PROTECTION', 'POSS: COCAINE',
       'THEFT OF LABOR/SERVICES', 'CREDIT CARD FRAUD',
       'AGGRAVATED DOMESTIC BATTERY: HANDS/FIST/FEET SERIOUS INJURY',
       'INTERFERENCE JUDICIAL PROCESS', 'RESIST/OBSTRUCT/DISARM OFFICER',
       'AGGRAVATED DOMESTIC BATTERY: OTHER DANG WEAPON',
       'INSTITUTIONAL VANDALISM', 'TO RESIDENCE',
       'TO CITY OF CHICAGO PROPERTY', 'ATTEMPT FORCIBLE ENTRY',
       'UNLAWFUL USE HANDGUN', 'ARMED: OTHER FIREARM', 'CHILD ABDUCTION',
       'FALSE/STOLEN/ALTERED TRP',
       'FINANCIAL IDENTITY THEFT $300 AND UNDER',
       'AGG PRO.EMP: OTHER DANG WEAPON', 'ATTEMPT: STRONGARM-NO WEAPON',
       'CHILD ABUSE', 'AGGRAVATED: OTHER DANG WEAPON',
       'HARASSMENT BY ELECTRONIC MEANS', 'UNLAWFUL POSS AMMUNITION',
       'AGGRAVATED VEHICULAR HIJACKING',
       'AGGRAVATED DOMESTIC BATTERY: KNIFE/CUTTING INST',
       'UNLAWFUL POSS OF HANDGUN', 'OTHER',
       'ARMED: OTHER DANGEROUS WEAPON', 'POCKET-PICKING',
       'AGG PO HANDS NO/MIN INJURY', 'OTHER OFFENSE',
       'ATTEMPT: ARMED-HANDGUN', 'UNLAWFUL USE/SALE AIR RIFLE',
       'MOB ACTION', 'OBSTRUCTING IDENTIFICATION',
       'UNLAWFUL USE OTHER DANG WEAPON', 'NON-AGGRAVATED',
       'TO STATE SUP LAND', 'THEFT/RECOVERY: AUTOMOBILE', 'FORGERY',
       'BOGUS CHECK', 'LIBRARY VANDALISM', 'DELIVERY CONTAINER THEFT',
       'AGGRAVATED', 'DECEPTIVE COLLECTION PRACTICES',
       'MANU/DELIVER:CRACK', 'AGG CRIMINAL SEXUAL ABUSE',
       'SOLICIT ON PUBLIC WAY', 'ATT: AUTOMOBILE',
       'POSS: CANNABIS MORE THAN 30GMS', 'OTHER CRIME AGAINST PERSON',
       'POSS: METHAMPHETAMINES', 'COUNTERFEITING DOCUMENT',
       'POSSESSION OF DRUG EQUIPMENT', 'TRUCK, BUS, MOTOR HOME',
       'UNLAWFUL POSS OTHER FIREARM', 'CRIMINAL SEXUAL ABUSE',
       'SEX OFFENDER: FAIL TO REGISTER', 'MANU/DEL:CANNABIS 10GM OR LESS',
       'ATTEMPT THEFT', 'PRO EMP HANDS NO/MIN INJURY',
       'VIOLATION OF CIVIL NO CONTACT ORDER', 'EMBEZZLEMENT',
       'SEXUAL EXPLOITATION OF A CHILD', 'OTHER VEHICLE OFFENSE',
       'ILLEGAL USE CASH CARD', 'VEHICLE TITLE/REG OFFENSE',
       'AGGRAVATED PO: OTHER DANG WEAP', 'THEFT BY LESSEE,NON-VEH',
       'ATTEMPT: ARMED-OTHER DANG WEAP', 'ANIMAL ABUSE/NEGLECT',
       'ATTEMPT ARSON', 'FINAN EXPLOIT-ELDERLY/DISABLED',
       'PROBATION VIOLATION', 'FORFEIT PROPERTY',
       'MANU/DELIVER:SYNTHETIC DRUGS', 'STOLEN PROP: BUY/RECEIVE/POS.',
       'AGG CRIM SEX ABUSE FAM MEMBER', 'POSS: HALLUCINOGENS',
       'OTHER VIOLATION', 'HOME INVASION', 'TO STATE SUP PROP',
       'VIO BAIL BOND: DOM VIOLENCE',
       'AGG: HANDS/FIST/FEET NO/MINOR INJURY', 'BY FIRE', 'POSS: PCP',
       'CYCLE, SCOOTER, BIKE W-VIN', 'ALTER/FORGE PRESCRIPTION',
       'ATTEMPT NON-AGGRAVATED', 'SOLICIT NARCOTICS ON PUBLICWAY',
       'ARMED:KNIFE/CUTTING INSTRUMENT',
       'ATTEMPT - FINANCIAL IDENTITY THEFT', 'INVOLUNTARY SERVITUDE',
       'POSS: BARBITUATES', 'INTIMIDATION', 'THEFT BY LESSEE,MOTOR VEH',
       'TO AIRPORT', 'RECKLESS FIREARM DISCHARGE',
       'SELL/GIVE/DEL LIQUOR TO MINOR', 'AGGRAVATED: OTHER',
       'UNLAWFUL USE OTHER FIREARM', 'AGGRAVATED OF A SENIOR CITIZEN',
       'OTHER WEAPONS VIOLATION', 'GUN OFFENDER: ANNUAL REGISTRATION',
       'POSS FIREARM/AMMO:NO FOID CARD', 'ILLEGAL POSSESSION CASH CARD',
       'BOMB THREAT', 'FALSE POLICE REPORT',
       'SALE/DIST OBSCENE MAT TO MINOR', 'CYCLE, SCOOTER, BIKE NO VIN',
       'UNLAWFUL INTERFERE/VISITATION', 'AGGRAVATED PO:KNIFE/CUT INSTR',
       'ARSON THREAT', 'VIOLENT OFFENDER: FAIL TO REGISTER NEW ADDRESS',
       'MANU/DELIVER:COCAINE', 'LIQUOR LICENSE VIOLATION',
       'AGG PRO.EMP:KNIFE/CUTTING INST', 'LICENSED PREMISE',
       'DEFACE IDENT MARKS OF FIREARM', 'ATTEMPT AGG: OTHER',
       'THEFT OF LOST/MISLAID PROP', 'SEX OFFENDER: FAIL REG NEW ADD',
       'MANU/DELIVER:PCP', 'POSS: AMPHETAMINES', 'PEEPING TOM',
       'ILLEGAL CONSUMPTION BY MINOR', 'COMPUTER FRAUD',
       'OTHER CRIME INVOLVING PROPERTY', 'CRIMINAL DRUG CONSPIRACY',
       'AGGRAVATED FINANCIAL IDENTITY THEFT',
       'MANU/DELIVER: HALLUCINOGEN', 'ARMED WHILE UNDER THE INFLUENCE',
       'PREDATORY', 'AGGRAVATED DOMESTIC BATTERY: HANDGUN',
       'ATTEMPT: AGGRAVATED', 'VIOLENT OFFENDER: ANNUAL REGISTRATION',
       'SOLICIT FOR BUSINESS', 'SOLICIT FOR PROSTITUTE',
       'ATT CRIM SEXUAL ABUSE', 'AGG: HANDS/FIST/FEET SERIOUS INJURY',
       'ATTEMPT POSSESSION NARCOTICS',
       'CONTRIBUTE DELINQUENCY OF A CHILD',
       'GUN OFFENDER: DUTY TO REGISTER', 'AGG PRO.EMP: HANDGUN',
       'VIOLATION GPS MONITORING DEVICE', 'OBSTRUCTING JUSTICE',
       'CHILD PORNOGRAPHY', 'CRIM SEX ABUSE BY FAM MEMBER',
       'UNAUTHORIZED VIDEOTAPING', 'AGGRAVATED OF A CHILD',
       'OBSCENE TELEPHONE CALLS', 'CONTRIBUTE CRIM DELINQUENCY JUVENILE',
       'POSS: LOOK-ALIKE DRUGS', 'AGG PRO EMP HANDS SERIOUS INJ',
       'ATTEMPT: ARMED-OTHER FIREARM', 'SEX RELATION IN FAMILY',
       'CHILD ABDUCTION/STRANGER', 'AGGRAVATED: OTHER FIREARM',
       'POSSESSION: SYNTHETIC MARIJUANA', 'IMPERSONATION',
       'VEHICULAR HIJACKING', 'ILLEGAL POSSESSION BY MINOR',
       'UNLAWFUL USE OF RECORDED SOUND', 'FOID - REVOCATION',
       'OTHER PROSTITUTION OFFENSE', 'OBSCENITY', 'FORCIBLE DETENTION',
       'CANNABIS PLANT', 'MANU/DELIVER: HEROIN(BRN/TAN)',
       'THEFT/RECOVERY: TRUCK,BUS,MHOME', 'AGGRAVATED PO: HANDGUN',
       'AGGRAVATED: KNIFE/CUT INSTR', 'VIOLATION OF SMOKING BAN',
       'LOST PASSPORT', 'AGGRAVATED - HANDGUN',
       'UNLAWFUL USE OF A COMPUTER', 'AGG SEX ASSLT OF CHILD FAM MBR',
       'MANU/DELIVER:BARBITUATES', 'CHILD ABANDONMENT',
       'AGGRAVATED DOMESTIC BATTERY - HANDGUN',
       'INDECENT SOLICITATION/CHILD', 'POSSESSION OF BURGLARY TOOLS',
       'UNIDENTIFIABLE RECORDING SOUND', 'TAMPER WITH MOTOR VEHICLE',
       'ESCAPE', 'ATTEMPT ARMED - KNIFE / CUTTING INSTRUMENT',
       'ATTEMPT: ARMED-KNIFE/CUT INSTR', 'STRONG ARM - NO WEAPON',
       'ATT AGG CRIMINAL SEXUAL ABUSE', 'GAME/AMUSEMENT DEVICE',
       'OBSTRUCTING SERVICE', 'UNLAWFUL RESTRAINT',
       'VIOLATION OF STALKING NO CONTACT ORDER', 'CALL OPERATION',
       'PIMPING', 'MANU/POSS. W/INTENT TO DELIVER: SYNTHETIC MARIJUANA',
       'ATTEMPT AGG: HANDGUN', 'RECKLESS HOMICIDE',
       'PUBLIC DEMONSTRATION', 'FALSE FIRE ALARM',
       'INTERFERE W/ HIGHER EDUCATION', 'CONT SUBS:FAIL TO MAINT RECORD',
       'POS: HYPODERMIC NEEDLE', 'EXTORTION',
       'ATTEMPT AGG: KNIFE/CUT INSTR', 'PAY TV SERVICE OFFENSES',
       'SEX OFFENDER: PROHIBITED ZONE', 'SOLICIT OFF PUBLIC WAY',
       'OBSCENE MATTER', 'GAME/CARDS', 'ATT: TRUCK, BUS, MOTOR HOME',
       'KIDNAPPING', 'MANU/DELIVER: METHAMPHETAMINES',
       'GUN OFFENDER: DUTY TO REPORT CHANGE OF INFORMATION',
       'CYBERSTALKING', 'DEL CONT SUBS TO PERSON <18',
       'UNLAWFUL SALE/DELIVERY OF FIREARM AT SCHOOL',
       'SELL/ADVERTISE FIREWORKS',
       'THEFT/RECOVERY: CYCLE, SCOOTER, BIKE W-VIN',
       'POSS. KEYS OR DEV.TO COIN MACH', 'EAVESDROPPING',
       'PROHIBITED PLACES', 'OTHER ARSON/EXPLOSIVE INCIDENT',
       'POS: EXPLOSIVE/INCENDIARY DEV', 'AGGRAVATED PO: KNIFE/CUT INSTR',
       'MANUFACTURE / DELIVER - CRACK',
       'VIOLENT OFFENDER: DUTY TO REGISTER', 'BRIBERY',
       'NOTIFICATION OF CIVIL NO CONTACT ORDER', 'ARMED - HANDGUN',
       'ATTEMPT: CYCLE, SCOOTER, BIKE W-VIN',
       'ATTEMPT AGG: OTHER FIREARM', 'AGGRAVATED - OTHER', 'BY EXPLOSIVE',
       'AGGRAVATED PO: OTHER FIREARM', 'TO FIRE FIGHT.APP.EQUIP',
       'CRIMINAL TRANSMISSION OF HIV', 'DELIVER CANNABIS TO PERSON <18',
       'INDECENT SOLICITATION/ADULT', 'UNLAWFUL SALE HANDGUN',
       'BOARD PLANE WITH WEAPON', 'FROM COIN-OP MACHINE/DEVICE',
       'AGGRAVATED - OTHER DANGEROUS WEAPON',
       'MANUFACTURE / DELIVER -  HEROIN (WHITE)', 'POSSESS - COCAINE',
       'POSS: HEROIN(BLACK TAR)', 'CONCEALED CARRY LICENSE REVOCATION',
       'INTOXICATING COMPOUNDS', 'ANIMAL FIGHTING', 'OFFICIAL MISCONDUCT',
       'HAZARDOUS MATERIALS VIOLATION', 'USE OF METAL PIERCING BULLETS',
       'OF UNBORN CHILD', 'POS: PORNOGRAPHIC PRINT',
       'COMMERCIAL SEX ACTS', 'VIOLATION OF SUMMARY CLOSURE',
       'INSURANCE FRAUD',
       'AGGRAVATED CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER',
       'ARSONIST: DUTY TO REGISTER', 'THEFT / RECOVERY - AUTOMOBILE',
       'ABUSE/NEGLECT: CARE FACILITY',
       'AGGRAVATED SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER',
       'POSSESS - HEROIN (WHITE)', 'SALE/DEL DRUG PARAPHERNALIA',
       'MANU/DELIVER:HEROIN(BLACK TAR)',
       'AGGRAVATED - KNIFE / CUTTING INSTRUMENT',
       'NON-CONSENSUAL DISSEMINATION PRIVATE SEXUAL IMAGES',
       'UNLAWFUL SALE OTHER FIREARM', 'AGGRAVATED COMPUTER TAMPERING',
       'EDUCATIONAL INTIMIDAITON', 'PATRONIZING A PROSTITUTE',
       'AGG PRO.EMP: OTHER FIREARM',
       'CRIMINAL SEXUAL ABUSE BY FAMILY MEMBER',
       'ARMED - OTHER DANGEROUS WEAPON', 'ARSONIST: ANNUAL REGISTRATION',
       'AGGRAVATED CRIMINAL SEXUAL ABUSE', 'POSSESS - CRACK',
       'FIRST DEGREE MURDER', 'ARMED - KNIFE / CUTTING INSTRUMENT',
       'UNLAWFUL POSSESSION - HANDGUN', 'POSSESS - HALLUCINOGENS',
       'AGG. PROTECTED EMPLOYEE - HANDS, FISTS, FEET, SERIOUS INJURY',
       'MANUFACTURE / DELIVER - HALLUCINOGEN',
       'ATTEMPT: CYCLE, SCOOTER, BIKE NO VIN', 'HARBOR RUNAWAY',
       'FINANCIAL ID THEFT:$300 &UNDER',
       'ATTEMPT FINANCIAL IDENTITY THEFT',
       'FINANCIAL ID THEFT: OVER $300', 'LIBRARY THEFT', 'PANDERING',
       'AGG: FINANCIAL ID THEFT', 'MINOR MISREPRESENT AGE',
       'POS: CHEMICAL/DRY-ICE DEVICE', 'ILLEGAL ILL LOTTERY',
       'ATTEMPT POSSESSION CANNABIS', 'CONCEALING/AIDING A FUGITIVE',
       'COMPELLING ORG MEMBERSHIP', 'FORNICATION',
       'AGGRAVATED DOMESTIC BATTERY: OTHER FIREARM',
       'ATTEMPT AGG: OTHER DANG WEAPON', 'KEEP PLACE OF PROSTITUTION',
       'JUVENILE PIMPING', 'SALE TOBACCO PRODUCTS TO MINOR',
       'AGGRAVATED OF A UNBORN CHILD', 'FIREARM REGISTRATION VIOLATION',
       'MONEY LAUNDERING', 'MANU/DELIVER:AMPHETAMINES',
       'BOOKMAKING/SPORTS', 'CAB OPERATION', 'SALE/DEL HYPODERMIC NEEDLE',
       'AGGRAVATED POLICE OFFICER - HANDGUN',
       'INTERFERE W/ EMERGENCY EQUIP', 'PATRONIZE JUVENILE PROSTITUTE',
       'COMPOUNDING A CRIME', 'THEFT BY LESSEE, MOTOR VEHICLE',
       'POSSESS - CANNABIS MORE THAN 30 GRAMS', 'CONTRABAND IN PRISON',
       'MANU/DELIVER:LOOK-ALIKE DRUG',
       'GUN OFFENDER NOTIFICATION-NO CONTACT',
       'AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MINOR INJURY',
       'AGG. DOMESTIC BATTERY - HANDS, FISTS, FEET, SERIOUS INJURY',
       'SEX OFFENDER - FAIL TO REGISTER',
       'AGGRAVATED PROTECTED EMPLOYEE - HANDGUN',
       'ATTEMPT ARMED - HANDGUN', 'FOUND PASSPORT',
       'INDECENT SOLICITATION OF A CHILD', 'UNLAWFUL USE - HANDGUN',
       'ATTEMPT CRIMINAL SEXUAL ABUSE', 'ATTEMPT AGGRAVATED',
       'SALE / DISTRIBUTE OBSCENE MATERIAL TO MINOR',
       'SEXUAL ASSAULT OF CHILD BY FAMILY MEMBER',
       'ARMED - OTHER FIREARM',
       'SEX OFFENDER - FAIL TO REGISTER NEW ADDRESS',
       'CYCLE, SCOOTER, BIKE WITH VIN',
       'ENDANGERING LIFE / HEALTH OF CHILD', 'INVOLUNTARY MANSLAUGHTER',
       'AGGRAVATED DOMESTIC BATTERY - KNIFE / CUTTING INSTRUMENT',
       'FINANCIAL EXPLOITATION OF AN ELDERLY OR DISABLED PERSON',
       'VEHICLE TITLE / REGISTRATION OFFENSE',
       'AGGRAVATED - OTHER FIREARM',
       'THEFT / RECOVERY - CYCLE, SCOOTER, BIKE WITH VIN',
       'POSSESS - CANNABIS 30 GRAMS OR LESS',
       'NON-CONSENSUAL DISSEMINATION OF PRIVATE SEXUAL IMAGES',
       'FROM COIN-OPERATED MACHINE OR DEVICE',
       'MANUFACTURE / DELIVER - SYNTHETIC DRUGS',
       'AGGRAVATED - HANDS, FISTS, FEET, SERIOUS INJURY',
       'POSSESS - METHAMPHETAMINE',
       'AGGRAVATED PROTECTED EMPLOYEE - KNIFE / CUTTING INSTRUMENT',
       'AGGRAVATED DOMESTIC BATTERY - OTHER DANGEROUS WEAPON',
       'ATTEMPT STRONG ARM - NO WEAPON', 'ATTEMPT AGGRAVATED - HANDGUN',
       'POSSESS FIREARM / AMMUNITION - NO FOID CARD',
       'UNLAWFUL USE - OTHER FIREARM',
       'PROTECTED EMPLOYEE - HANDS, FISTS, FEET, NO / MINOR INJURY',
       'MANUFACTURE / DELIVER - COCAINE',
       'POSSESS - HEROIN (TAN / BROWN TAR)', 'ATTEMPT - AUTOMOBILE'],
      dtype=object)

In [16]:
df.drop(['Unnamed: 0','Case Number','Updated On','IUCR','FBI Code','ID','Block'],axis=1,inplace=True)

In [17]:
df['Date'] = df['Date'].astype('datetime64[ns]')

In [18]:
df.head(5)

,Date,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude,Location
0,2015-09-05 12:45:00,NARCOTICS,POSS: HEROIN(BRN/TAN),SIDEWALK,True,False,1412,14.0,35.0,21.0,1152037,1920384,2015,41.937406,-87.716650,"(41.937405765, -87.716649687)"
1,2015-09-05 11:00:00,BATTERY,SIMPLE,SMALL RETAIL STORE,False,False,1623,16.0,45.0,11.0,1137969,1934340,2015,41.975968,-87.768014,"(41.975968415, -87.768014257)"
2,2015-09-05 07:00:00,BURGLARY,UNLAWFUL ENTRY,APARTMENT,False,False,1124,11.0,2.0,27.0,1156926,1899592,2015,41.880253,-87.699247,"(41.880252868, -87.69924661)"
3,2015-09-05 14:44:00,ASSAULT,SIMPLE,SIDEWALK,True,False,1722,17.0,39.0,14.0,1147525,1931300,2015,41.967448,-87.732951,"(41.967448012, -87.732951137)"
4,2015-09-05 11:20:00,ROBBERY,STRONGARM - NO WEAPON,STREET,False,False,2011,20.0,40.0,2.0,1157555,1937753,2015,41.984957,-87.695895,"(41.984956576, -87.69589518)"

In [19]:
df.dropna(inplace=True)

In [20]:
df['Community Area'] = df['Community Area'].astype(int)

In [21]:
df['Primary Type'].unique()

'''
we can agg some similar crimes such as theft/robbery or burglary. for now we will keep as.

-> two non criminal values - agg

-> sex offense and sex assalt can be agg

-> Narcotic Violation and narcotics -agg


'''

'\nwe can agg some similar crimes such as theft/robbery or burglary. for now we will keep as.\n\n-> two non criminal values - agg\n\n-> sex offense and sex assalt can be agg\n\n-> Narcotic Violation and narcotics -agg\n\n\n'

In [22]:
df['Primary Type'].replace("NON-CRIMINAL (SUBJECT SPECIFIED)", "NON-CRIMINAL",inplace=True)
df['Primary Type'].replace("NON - CRIMINAL", "NON-CRIMINAL",inplace=True)
df['Primary Type'].replace("OTHER NARCOTIC VIOLATION", "NARCOTICS",inplace=True)

In [23]:
df['Primary Type'].unique()

array(['NARCOTICS', 'BATTERY', 'BURGLARY', 'ASSAULT', 'ROBBERY', 'THEFT',
       'DECEPTIVE PRACTICE', 'OTHER OFFENSE', 'SEX OFFENSE',
       'CRIMINAL DAMAGE', 'MOTOR VEHICLE THEFT', 'CRIMINAL TRESPASS',
       'OFFENSE INVOLVING CHILDREN', 'PUBLIC PEACE VIOLATION', 'GAMBLING',
       'INTERFERENCE WITH PUBLIC OFFICER', 'WEAPONS VIOLATION',
       'CRIM SEXUAL ASSAULT', 'PROSTITUTION', 'STALKING', 'ARSON',
       'HUMAN TRAFFICKING', 'INTIMIDATION', 'LIQUOR LAW VIOLATION',
       'OBSCENITY', 'KIDNAPPING', 'PUBLIC INDECENCY',
       'CONCEALED CARRY LICENSE VIOLATION', 'NON-CRIMINAL',
       'CRIMINAL SEXUAL ASSAULT', 'HOMICIDE'], dtype=object)

In [24]:
df['Year'].value_counts()

2009    77018
2010    73870
2011    70323
2012    67195
2013    61361
2014    54769
2016    53424
2017    53007
2018    52378
2015    51633
2019    51201
Name: Year, dtype: int64

# Merging Social Economic stats into our DataFrame

In [25]:
df2 =  pd.read_csv('./data/SocialEconomic indicators Chicago.csv')

In [26]:
df2

,Community Area Number,COMMUNITY AREA NAME,PERCENT OF HOUSING CROWDED,PERCENT HOUSEHOLDS BELOW POVERTY,PERCENT AGED 16+ UNEMPLOYED,PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA,PERCENT AGED UNDER 18 OR OVER 64,PER CAPITA INCOME,HARDSHIP INDEX
0,1,Rogers Park,7.7,23.6,8.7,18.2,27.5,23939,39
1,2,West Ridge,7.8,17.2,8.8,20.8,38.5,23040,46
2,3,Uptown,3.8,24.0,8.9,11.8,22.2,35787,20
3,4,Lincoln Square,3.4,10.9,8.2,13.4,25.5,37524,17
4,5,North Center,0.3,7.5,5.2,4.5,26.2,57123,6
...,...,...,...,...,...,...,...,...,...
72,73,Washington Height,1.1,16.9,20.8,13.7,42.6,19713,48
73,74,Mount Greenwood,1.0,3.4,8.7,4.3,36.8,34381,16
74,75,Morgan Park,0.8,13.2,15.0,10.8,40.3,27149,30
75,76,O'Hare,3.6,15.4,7.1,10.9,30.3,25828,24
76,77,Edgewater,4.1,18.2,9.2,9.7,23.8,33385,19

In [27]:
df2.columns

Index(['Community Area Number', 'COMMUNITY AREA NAME',
       'PERCENT OF HOUSING CROWDED', 'PERCENT HOUSEHOLDS BELOW POVERTY',
       'PERCENT AGED 16+ UNEMPLOYED',
       'PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA',
       'PERCENT AGED UNDER 18 OR OVER 64', 'PER CAPITA INCOME ',
       'HARDSHIP INDEX'],
      dtype='object')

In [28]:
df2.rename(columns={'Community Area Number':'Community Area'}, inplace=True)

In [29]:
df3 = df.merge(df2,how='outer',on=['Community Area'])

In [30]:
df3.dropna(inplace=True)

In [31]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 666177 entries, 0 to 666176
Data columns (total 24 columns):
 #   Column                                        Non-Null Count   Dtype
---  ------                                        --------------   -----
 0   Date                                          666177 non-null  datetime64[ns]
 1   Primary Type                                  666177 non-null  object
 2   Description                                   666177 non-null  object
 3   Location Description                          666177 non-null  object
 4   Arrest                                        666177 non-null  bool
 5   Domestic                                      666177 non-null  bool
 6   Beat                                          666177 non-null  int64
 7   District                                      666177 non-null  float64
 8   Ward                                          666177 non-null  float64
 9   Community Area                                666177 non-null  int32
 10  X Coordinate                                  666177 non-null  int64
 11  Y Coordinate                                  666177 non-null  int64
 12  Year                                          666177 non-null  int64
 13  Latitude                                      666177 non-null  float64
 14  Longitude                                     666177 non-null  float64
 15  Location                                      666177 non-null  object
 16  COMMUNITY AREA NAME                           666177 non-null  object
 17  PERCENT OF HOUSING CROWDED                    666177 non-null  float64
 18  PERCENT HOUSEHOLDS BELOW POVERTY              666177 non-null  float64
 19  PERCENT AGED 16+ UNEMPLOYED                   666177 non-null  float64
 20  PERCENT AGED 25+ WITHOUT HIGH SCHOOL DIPLOMA  666177 non-null  float64
 21  PERCENT AGED UNDER 18 OR OVER 64              666177 non-null  float64
 22  PER CAPITA INCOME                             666177 non-null  float64
 23  HARDSHIP INDEX                                666177 non-null  float64
dtypes: bool(2), datetime64[ns](1), float64(11), int32(1), int64(4), object(5)
memory usage: 115.6+ MB

In [32]:
df3.to_csv('crime_test.csv',index=False)